version: "2.3"

services:
    taxi-userver-clang-tidy:
        image: registry.yandex.net/taxi/taxi-integration-xenial-base
        environment:
        - BUILD_DIR=${BUILD_DIR:-/taxi/userver/build}
        - CC
        - CLANG_TIDY_BINARY
        - CMAKE_OPTS
        - CXX
        - IS_TEAMCITY
        - LANG=ru_RU.UTF-8
        - NPROCS
        volumes:
        - .:/taxi/userver:rw
        - ./tools/dockertest:/taxi/tools:rw
        working_dir: /taxi/userver/
        command: /taxi/tools/userver-clang-tidy.sh
