version: "2.3"

services:
    taxi-userver-clang-tidy:
        image: registry.yandex.net/taxi/taxi-integration-xenial-base
        network_mode: bridge
        environment:
          - BUILD_DIR=${BUILD_DIR:-/taxi/userver/build}
          - CC
          - CLANG_TIDY_BINARY
          - CMAKE_OPTS
          - CXX
          - IS_TEAMCITY
          - LANG=ru_RU.UTF-8
          - NPROCS
        volumes:
          - .:/taxi/userver:rw
          - ./tools/dockertest:/taxi/tools:rw
        working_dir: /taxi/userver/
        command: /taxi/tools/userver-clang-tidy.sh

    taxi-userver-bionic:
        image: registry.yandex.net/taxi/taxi-bionic-base
        container_name: taxi-userver-bionic
        entrypoint: /taxi/userver/tools/dockertest/run_as_user.sh
        network_mode: bridge
        environment:
          - CC
          - CXX
          - BUILD_DIR=${BUILD_DIR:-/taxi/userver/build}
          - BUILD_TYPE=${BUILD_TYPE:-Release}
          - CCACHE_DIR=/taxi/ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS=${CMAKE_OPTS}
          - DISTCC_HOSTS
          - IS_TEAMCITY
          - NPROCS
          - LANG=ru_RU.UTF-8
        volumes:
          - .:/taxi/userver:rw
          - ${CCACHE_DIR:-~/.ccache}:/taxi/ccache:rw
        working_dir: /taxi/userver

    taxi-userver-tests:
        image: registry.yandex.net/taxi/taxi-integration-xenial-base:${VERSION:-latest}
        privileged: true
        mem_limit: 40G
        network_mode: bridge
        environment:
          - BUILD_DIR=${BUILD_DIR:-/taxi/userver/build}
          - CC
          - CCACHE_DIR=/taxi/ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/taxi/cores
          - CONTAINER_NAME=taxi-userver-tests
          - CXX
          - IS_TEAMCITY
          - NPROCS
          - PULL_REQUEST_TYPE
        volumes:
          - .:/taxi/userver:rw
          - ./tools/dockertest:/taxi/tools:ro
          - ${CCACHE_DIR:-~/.ccache}:/taxi/ccache:rw
          - ${TC_CORES_DIR:-./cores}:/taxi/cores:rw
        working_dir: /taxi/userver/
        command: /taxi/userver/tools/userver-tests.sh
