linters:
    package-dirs:
      - .
      - submodules/codegen
    jsonfmt:
        disable-paths-wildcards:
          - .mypy_cache/*
    clang-format:
        disable-paths-wildcards:
          - third_party/*
          - uboost_coro/*
