# yaml
components_manager:
    components:                       # Configuring components that were registered via component_list
        # /// [pg-cache config]
        # yaml
        auth-database:
            dbconnection: 'postgresql://testsuite@localhost:15433/postgres'
            blocking_task_processor: fs-task-processor
            dns_resolver: async

        auth-pg-cache:
            pgcomponent: auth-database
            update-interval: 10s
        # /// [pg-cache config]

        # /// [hello config]
        # yaml
        handler-hello:
            path: /v1/hello
            task_processor: main-task-processor
            method: GET
            auth:           # Authorization config for this handler
                types:
                  - bearer  # Authorization type that was specified in main()
                scopes:     # Required user scopes for that handler
                  - read
                  - hello
        # /// [hello config]

        testsuite-support:

        server:
            listener:                 # configuring the main listening socket...
                port: 8095            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        dynamic-config:                      # Dynamic config storage options, do nothing
            defaults:
                POSTGRES_CONNECTION_POOL_SETTINGS:
                    key-value-database:
                        max_pool_size: 15
                        max_queue_size: 200
                        min_pool_size: 8
                POSTGRES_CONNECTION_SETTINGS:
                    key-value-database:
                        max-ttl-sec: 60
                        recent-errors-threshold: 100000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500
                POSTGRES_HANDLERS_COMMAND_CONTROL:
                    /v1/key-value:
                        DELETE:
                            network_timeout_ms: 500
                            statement_timeout_ms: 250
                POSTGRES_QUERIES_COMMAND_CONTROL:
                    sample_select_value:
                        network_timeout_ms: 70
                        statement_timeout_ms: 40
                    sample_transaction_insert_key_value:
                        network_timeout_ms: 200
                        statement_timeout_ms: 150
                POSTGRES_STATEMENT_METRICS_SETTINGS:
                    key-value-database:
                        max_statement_metrics: 5
        dns-client:
            fs-task-processor: fs-task-processor

    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: 4         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: 4

    default_task_processor: main-task-processor
