# yaml
server-name: sample-production-service 1.0
service-name: sample-production-service
logger-level: info

config-server-url: http://localhost:8083/
monitor-server-port: 8085

is-testing: false

userver-dumps-root: /var/cache/production_service/userver-dumps/
access-log-path: /var/log/production_service/access.log
access-tskv-log-path: /var/log/production_service/access_tskv.log
default-log-path: /var/log/production_service/server.log
secdist-path: /etc/production_service/secure-data.json
unix-socket: /var/run/production_service/service.socket

config-cache: /var/cache/production_service/config_cache.json
config-fallback: /etc/production_service/dynamic_config.json
